### ISSUE TITLE
python3 run_training.py  error

### ISSUE THREAD

**Issue by ytgcljj** [overfitover/pixor_pytorch#1]
launchx-500-16-2@launchx500162-System-Product-Name:~/github/pixor_pytorch$ python3 run_training.py 
There are 58 images in txt file
Found 58 Velodyne scans...
done.
There are 44 images in txt file
Found 44 Velodyne scans...
done.
loc_loss: 0.00000 | cls_loss: 0.14906
Traceback (most recent call last):
  File "run_training.py", line 151, in <module>
    train(epoch)
  File "run_training.py", line 79, in train
    total_loss += float(loss.data[0])
IndexError: invalid index of a 0-dim tensor. Use tensor.item() to convert a 0-dim tensor to a Python number

**Comment by overfitover** [comment]
You might have to change loss.data[0] to loss.item() as indicated in the error message.

**Comment by ytgcljj** [comment]
thanks

**Comment by ytgcljj** [comment]
![_20190108093114](https://user-images.githubusercontent.com/27713475/50804289-3debe480-1328-11e9-8b23-13d8941f8af8.jpg)

**Comment by ytgcljj** [comment]
I turn on how to display this, it feels like a crash.

**Comment by ytgcljj** [comment]
Another question is, if I want to test outdoors, how do I do it?

**Comment by overfitover** [comment]
Close the Figure1.
There are some problems,but I am too lazy to fit it.

**Comment by overfitover** [comment]
https://github.com/overfitover/pixor_ovo
这个是修改过的版本．但是是处理彩色点云的．你可以参考一下．test outdoors是什么意思？
