### ISSUE TITLE
How to evaluate the trained model

### ISSUE THREAD

**Issue by andrearama** [overfitover/pixor_pytorch#10]
Great work, thanks for sharing it!

I was wondering if there was any way to evaluate the results in a quantitative metrics (as shown in the paper, for example with AP ).
As far as I understood it is still something on the to-do list, but maybe you could point me to some other resource which I could easily use for this case.

Thanks!
Andrea

**Comment by overfitover** [comment]
@andrearama 
您可以参考这个实现。https://github.com/philip-huang/PIXOR。他有写评估函数。

**Comment by andrearama** [comment]
谢谢,
我看一下
