### ISSUE TITLE
有没有评估一下mAP？

### ISSUE THREAD

**Issue by deepmeng** [overfitover/pixor_pytorch#2]

**Comment by overfitover** [comment]
@deepmeng 
没有做这个。
你可以把结果保存成kitti的评估形式，利用kitti的评估来做一下。

**Comment by deepmeng** [comment]
@overfitover 你好，我刚开始做雷达目标检测这块，我觉得pixor_pytorch是一个不错的入门案例。现在遇到的唯一问题是如何把bird view下的检测结果转换为KITTI label格式下对应的坐标？ 有没有一些现有的工具和方法？ 不胜感激！

**Comment by overfitover** [comment]
@deepmeng 
建议你去看看avod、F-pointnet的开源代码。这些代码里面体现的细节更好一些。

**Comment by deepmeng** [comment]
好的，我正在研究，谢谢答复！
