### ISSUE TITLE
Why there is a "SElayer" after the first convolution layer in "backbone"?

### ISSUE THREAD

**Issue by qiqihaer** [overfitover/pixor_pytorch#8]
Thanks for the implementation. What role dose the "SElayer" play in the "backbone"? Are there any reference about SElayer? Since I have never seen it before. Thanks a lot!!!

**Comment by overfitover** [comment]
@qiqihaer 
You can check out the SE module in SENet. You will know that such an implementation will enhance the expression of shallow features.
https://github.com/hujie-frank/SENet

**Comment by qiqihaer** [comment]
Thank you very much.
